[DO NOT MERGE] Remove basic auth
alphagov/govuk-coronavirus-vulnerable-people-form pull request #140
Opened 2020-03-23 08:02 UTC by theseanything

2020-03-23 08:03 UTC, brucebolt approved these changes

2020-03-23 09:43 UTC, bilbof commented
This'll remove the auth from staging too, right? Maybe we should set a flag in the deploy with `cf` to override this instead.

2020-03-23 09:48 UTC, paulmsmith commented
Interested spectator 👋  - Wishing you all the best. I believe you can create 'draft' pull requests in Github these days so you don't have to worry about accidental untimely merging. You have control of changing it from draft to ready.

2020-03-23 09:55 UTC, issyl0 commented
@paulmsmith Thanks for the head's up and the good wishes! We're working flat out here!

2020-03-23 10:22 UTC, paulmsmith commented
I can see @nickcolley and all you have been busy over the weekend. I'll keep an eye on your issues, if I can do quick grunt work and raise pull requests I will.

2020-03-23 10:23 UTC, nickcolley commented
@paulmsmith thanks for the offer mate but we're good for now, thank you again for thinking about us. :+1:

2020-03-23 10:23 UTC, paulmsmith commented
@nickcolley No worries. More hands does add complication too. Ping me if there is anything.

2020-03-23 10:34 UTC, richardTowers requested changes
I think we need to remove:

```
    REQUIRE_BASIC_AUTH: true
```

From manifest.yml too

2020-03-23 11:13 UTC, richardTowers commented on concourse/tasks/deploy-to-govuk-paas.yml
> +      if [[ "${BASIC_AUTH_PASSWORD:-}" = "true" ]]; then
```suggestion
      if [[ "${REQUIRE_BASIC_AUTH:-}" = "true" ]]; then
```

2020-03-24 12:28 UTC, richardTowers approved these changes

2020-03-24 12:28 UTC, merged

2020-03-24 12:47 UTC, sarahseewhy commented
NOTE
@richardTowers and I un-paused the pipeline to deploy the application in production before merging this pull request.

This caused a basic-auth pop-up to appear for users for a 30 second period while we fixed the issue.

IMPACT
- request affected: ~2,000
- duration of incident: ~30 seconds
- time to resolution: ~30 seconds

Once Rich and I realised the mistake we merged the PR and un-paused the pipeline again. 

All fixed.