Return 200 for validation errors
alphagov/govuk-coronavirus-vulnerable-people-form pull request #155
Opened 2020-03-23 15:41 UTC by bilbof

These will get logged anyway if we have the log level set to info.

https://trello.com/c/tZRgrJPt/161-style-422-errors-nicely-since-were-serving-a-lot-of-them

2020-03-23 15:44 UTC, huwd commented on spec/controllers/coronavirus_form/basic_care_needs_controller_spec.rb
> -      expect(response).to have_http_status(:unprocessable_entity)
Does render templat imply a 200 or can we do `to_have_http_status(:success)` or something similar?

2020-03-23 15:44 UTC, huwd approved these changes

2020-03-24 14:35 UTC, injms requested changes
I'd like to make sure that we are actually logging the validation errors before this is merged in and we lose the ability to tell what parts of the form that users are struggling with.

2020-03-31 14:37 UTC, bilbof commented
I'd prefer not to do this, since having 422s in the logs is quite useful. I'm going to close this for now.

2020-03-31 14:37 UTC, closed without merging