Improve email address validation
alphagov/govuk-coronavirus-vulnerable-people-form pull request #277
Opened 2020-04-22 12:46 UTC by issyl0

- We were previously only validating that the email address contains the
  `@` character. That's not enough, as people can enter invalid email
  addresses, like ones with commas in, if they mistype `.com` or
  somesuch.
- Our downstream data consumers were finding this out the hard way when
  they tried to use the email addresses to contact people.
- This uses the Python implementation at https://emailregex.com/ to
  validate the email address doesn't contain any invalid characters.

https://trello.com/c/hGSi37CH/315-email-address-field-accepts-commas

2020-04-22 15:34 UTC, bilbof requested changes
If possible could we have some more tests of this helper, with various email combinations? Just want to make sure we have various examples of invalid/valid emails in the test cases.

2020-04-22 16:25 UTC, bilbof approved these changes
🚀 awesome, thank you so much

2020-04-22 16:34 UTC, issyl0 commented
Thanks for the review, Bill. We can't merge this until we've heard back from DWP.

2020-04-22 16:39 UTC, leenagupte submitted a review, later dismissed
Needs stakeholder approval.

2020-04-24 09:55 UTC, huwd commented
@issyl0 [Steve has confirmed ](https://trello.com/c/hGSi37CH/315-email-address-field-accepts-commas)this can be merged without waiting for a reply

So looks like we can resolve that conflict and :rocket:

2020-04-24 11:45 UTC, merged